### PR TITLE
impl CountDown for SYST; add listen/unlisten to Timer; add reactive-blinky and motor examples

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e377a04 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e377a04f9a109b01ee1ff0ab1ec9e6b191820bc0 with merge 379a82d3f4d831cb64a8aa128a9bf038b0d0d4fb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f103xx-hal/builds/333315041?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 379a82d3f4d831cb64a8aa128a9bf038b0d0d4fb to master...

**Pull request merged**
