### PR TITLE
Update dependency versions to fix `panic-fmt` lang item not found

### PR DESCRIPTION
**Pull request by chocol4te**

### CODE REVIEW

**Comment by chocol4te** [comment]
bors try

**Comment by jamesmunns** [comment]
bors try

**Comment by jamesmunns** [comment]
Hm. @japaric is on vacation, and I'm not sure who the other reviewers are for this. Hopefully he sees this.

Thanks for the contribution @chocol4te!

**Comment by japaric** [comment]
Thanks @chocol4te!

bors r+

**Pull request merged**
