### PR TITLE
DMA API

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 64583dd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 64583ddc063ec104b4a68db40341d5d069b3a686 with merge 6656271519f863aaf081857478b69b0610ccfa26...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/stm32f103xx-hal/builds/333503924?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 76972ea has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 76972ead82a0528046a24c520cc00ca92348870e with merge ad0302d33d1729501126279ad0efbd365285b6f3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f103xx-hal/builds/333505988?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing ad0302d33d1729501126279ad0efbd365285b6f3 to master...

**Pull request merged**
