### PR TITLE
disable ThinLTO

### LINKED ISSUE #44: Programm size leaps
2018-01-26
Mint 18.3
rustc 1.25.0-nightly (5965b7901 2018-01-19)

| example | size |
| ----- | ----- |
| blinky | 2396 |
| delay | 2460 |
| hello | 10584 |
| led | 804 |
| motor | 14222 |
| mpu9250 | 16150 |
| pwm | 12196 |
| qei | 12960 |
| reactive-blinky | 2160 |
| reactive-serial-circ | 12362 |
| serial-dma-circ | 12290 |
| serial-dma-rx | 2548 |
| serial-dma-tx | 2700 |
| serial | 12442 |

In serial example one string:
`let received = block!(rx.read()).unwrap();`
adds +9614 bytes

### PR DESCRIPTION
**Pull request by japaric**
closes #44

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 70f30a2 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 70f30a22025c21c73c9939b19551a1ffd2b38f4f with merge fc6a5d441d899d1f01c59ae0cb98d5f3cbc81aa3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f103xx-hal/builds/333659597?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing fc6a5d441d899d1f01c59ae0cb98d5f3cbc81aa3 to master...

**Pull request merged**
