### PR TITLE
modify ENR; don't write to it

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit bd7b397 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit bd7b39799691172123924abb95eff01658530e54 with merge 9f80811a6026f0849ce2afee5baf0cf086563b65...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f103xx-hal/builds/333558371?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 9f80811a6026f0849ce2afee5baf0cf086563b65 to master...

**Pull request merged**
