### PR TITLE
Reintroduced pull_down_input, pull_up_input for GPIOs

### PR DESCRIPTION
**Pull request by TeXitoi**
I found this commit on @e-matteson repo that seems to take it from @burrbull repo. It's simple and working fine, and I need it to remove that useless 10k resistor that pull up my buttons.

OK @japaric @e-matteson @burrbull?

### CODE REVIEW

**Comment by e-matteson** [comment]
Similarly, I forked it just to save a snapshot to use as a dependency. I can say that I've successfully used it to enable pullups on a blue-pill board, but haven't thoroughly tested or reviewed it.

**Comment by kellerkindt** [comment]
Neat! I had an actual use case for this a few weeks back, but then used actual pull-up-resistors instead. I would like to test it, but on the one hand I also only have the bluepill board at hand and on the other hand probably have not enough time in the near future to give it a more in-deepth test :(

**Comment by TeXitoi** [comment]
I've ttested on a blue pill with a button connected to ground with mc pull up, and connected to VCC with mc pull down. Everything worked. I've reviewed the code and everything seems fine.

**Comment by TheZoq2** [comment]
Looks very similar to my implementation here: https://github.com/TheZoq2/stm32f103xx-hal/commit/5c11436ed4f4e8e4a97eb2486bff9219d5d0c41d

**Comment by gbip** [comment]
Maybe this should be merged then ? Is japaric still the main maintainer of this crate ?

**Comment by TeXitoi** [comment]
AFAIK, @japaric is the only one that can merge.

**Comment by gbip** [comment]
> I believe so as well, and I also believe that he is pretty busy with other embedded-wg work. Perhaps someone else could step in as co-maintainer until @japaric has more time. I'd be happy to do it if required and it also seems like @TeXitoi would make a very good candidate since they are already inoffically reviewing a bunch of PRs

Check out this [issue](https://github.com/rust-embedded/wg/issues/224) in the workgroup repository :wink:

**Comment by kellerkindt** [comment]
Kinda relates #51

**Pull request merged**
