### PR TITLE
add Serial.{un,}listen; fix return type of Serial.read_exact; add 2 more MPU9250 examples

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b0299cc has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b0299cc1e42a498f2bc13b28b142afa217d52b71 with merge 9fa23af973919cb8e2ebe35ccceec79663a37336...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/stm32f103xx-hal/builds/335713363?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 9fa23af973919cb8e2ebe35ccceec79663a37336 to master...

**Pull request merged**
